# Generated by Django 5.2.17 on 2026-10-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('gateway_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('new', 'New'), ('spare', 'Spare'), ('connected', 'Connected'), ('stale', 'Stale'), ('disconnected', 'Disconnected'), ('suspended', 'Suspended'), ('retired', 'Retired')], default='new', max_length=16)),
                ('status_since', models.DateTimeField()),
                ('suspended_reason', models.TextField(null=True)),
                ('command_state', models.CharField(choices=[('running', 'Running'), ('stop_pending', 'Stop Pending'), ('stopped', 'Stopped'), ('stop_failed', 'Stop Failed'), ('resume_pending', 'Resume Pending'), ('resume_failed', 'Resume Failed')], default='running', max_length=16)),
                ('command_state_since', models.DateTimeField()),
                ('last_heartbeat_at', models.DateTimeField(null=True)),
                ('last_qualifying_at', models.DateTimeField(null=True)),
                ('disconnected_since', models.DateTimeField(null=True)),
                ('last_auth_failure_at', models.DateTimeField(null=True)),
                ('collecting_after_stop', models.BooleanField(default=False)),
            ],
        ),
    ]
