# Generated by Django 5.2.17 on 2026-10-06 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateways', '0001_initial'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_id', models.CharField(max_length=128)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('session', models.CharField(choices=[('ok', 'Ok'), ('auth_failed', 'Auth Failed')], max_length=16)),
                ('received_at', models.DateTimeField()),
                ('body_hash', models.CharField(max_length=64)),
                ('ignored', models.JSONField(default=list)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='gateways.gateway')),
            ],
        ),
        migrations.CreateModel(
            name='CycleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_at', models.DateTimeField()),
                ('outcome', models.CharField(choices=[('readings', 'Readings'), ('no_readings', 'No Readings'), ('could_not_read', 'Could Not Read'), ('timed_out', 'Timed Out')], max_length=16)),
                ('reported_outcome', models.CharField(max_length=16)),
                ('batch_id', models.CharField(max_length=128, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='gateways.cycle')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_results', to='gateways.gateway')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_results', to='sensors.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField()),
                ('session', models.CharField(choices=[('ok', 'Ok'), ('auth_failed', 'Auth Failed')], max_length=16)),
                ('received_at', models.DateTimeField()),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='gateways.gateway')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cycle',
            constraint=models.UniqueConstraint(fields=('gateway', 'cycle_id'), name='cycle_unique_per_gateway'),
        ),
        migrations.AddIndex(
            model_name='cycleresult',
            index=models.Index(fields=['sensor', 'finished_at'], name='gateways_cy_sensor__f6ace2_idx'),
        ),
        migrations.AddIndex(
            model_name='cycleresult',
            index=models.Index(fields=['batch_id'], name='gateways_cy_batch_i_a28e50_idx'),
        ),
        migrations.AddConstraint(
            model_name='cycleresult',
            constraint=models.UniqueConstraint(fields=('cycle', 'sensor'), name='one_result_per_sensor_per_cycle'),
        ),
        migrations.AddConstraint(
            model_name='heartbeat',
            constraint=models.UniqueConstraint(fields=('gateway', 'sent_at', 'session'), name='heartbeat_unique'),
        ),
    ]
