# Generated by Django 5.2.17 on 2026-10-06 11:31

import django.db.models.deletion
import gateways.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateways', '0002_heartbeats_cycles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('command_id', models.CharField(default=gateways.models.new_command_id, max_length=32, primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('stop', 'Stop'), ('resume', 'Resume')], max_length=8)),
                ('issued_at', models.DateTimeField()),
                ('timeout_at', models.DateTimeField()),
                ('superseded', models.BooleanField(default=False)),
                ('timed_out', models.BooleanField(default=False)),
                ('acked_at', models.DateTimeField(null=True)),
                ('ack_received_at', models.DateTimeField(null=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='gateways.gateway')),
            ],
        ),
        migrations.CreateModel(
            name='StopPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(null=True)),
                ('has_readings', models.BooleanField(default=False)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_periods', to='gateways.gateway')),
                ('stop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stop_period', to='gateways.command')),
            ],
        ),
        migrations.AddIndex(
            model_name='command',
            index=models.Index(fields=['timed_out', 'timeout_at'], name='gateways_co_timed_o_0d230f_idx'),
        ),
        migrations.AddConstraint(
            model_name='command',
            constraint=models.UniqueConstraint(fields=('gateway', 'seq'), name='command_seq_unique_per_gateway'),
        ),
    ]
