# Generated by Django 5.2.17 on 2026-10-06 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gateways', '0002_heartbeats_cycles'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('sensor_id', models.CharField(max_length=128)),
                ('readings', models.JSONField()),
                ('body_hash', models.CharField(max_length=64)),
                ('received_at', models.DateTimeField()),
                ('processing', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('partially_processed', 'Partially Processed'), ('retrying', 'Retrying'), ('quarantined', 'Quarantined')], default='received', max_length=24)),
                ('reason', models.CharField(max_length=32, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(null=True)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('accepted_count', models.PositiveIntegerField(default=0)),
                ('latest_accepted_taken_at', models.DateTimeField(null=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='gateways.gateway')),
            ],
        ),
        migrations.CreateModel(
            name='QuarantinedReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('reading_id', models.CharField(max_length=128, null=True)),
                ('reason', models.CharField(max_length=32)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantined', to='batches.batch')),
            ],
            options={
                'ordering': ['batch', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('reading_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('taken_at', models.DateTimeField()),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=8)),
                ('content_hash', models.CharField(max_length=64)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted', to='batches.batch')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='gateways.gateway')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensor')),
            ],
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['processing', 'next_attempt_at'], name='batches_bat_process_ce6af9_idx'),
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['sensor', 'taken_at'], name='batches_rea_sensor__9798f6_idx'),
        ),
    ]
