# Generated by Django 5.2.17 on 2026-10-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaultInjection',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('processing_failures', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
