# Generated by Django 5.2.17 on 2026-10-06 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gateways', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('temperature', 'Temperature'), ('rain', 'Rain'), ('wind', 'Wind')], max_length=16)),
                ('created_at', models.DateTimeField()),
                ('lifecycle', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('dormant', 'Dormant'), ('sampling', 'Sampling'), ('retired', 'Retired'), ('decommissioned', 'Decommissioned')], default='pending', max_length=16)),
                ('lifecycle_reason', models.TextField(null=True)),
                ('lifecycle_since', models.DateTimeField()),
                ('collection', models.CharField(default='not_checked', max_length=24)),
                ('coverage', models.CharField(default='none', max_length=16)),
                ('quiet_checked_days', models.PositiveIntegerField(default=0)),
                ('sampling_cycles_done', models.PositiveIntegerField(default=0)),
                ('next_evaluation_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('reason', models.TextField()),
                ('at', models.DateTimeField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='sensors.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='CoverageAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(null=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='gateways.gateway')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='sensors.sensor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('valid_to__isnull', True)), fields=('sensor', 'gateway'), name='one_open_assignment_per_pair')],
            },
        ),
    ]
