# Generated by Django 5.2.17 on 2026-10-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='reconcile_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
