# Generated by Django 5.2.17 on 2026-10-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClockState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('now', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ConfigVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateTimeField(unique=True)),
                ('recorded_at', models.DateTimeField()),
                ('quiet_days_before_dormant', models.PositiveIntegerField()),
                ('dormant_wait_hours', models.PositiveIntegerField()),
                ('sampling_window_hours', models.PositiveIntegerField()),
                ('sampling_cycles_before_retired', models.PositiveIntegerField()),
                ('stale_after_hours', models.PositiveIntegerField()),
                ('command_timeout_minutes', models.PositiveIntegerField()),
                ('batch_deadline_hours', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['effective_from'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=16)),
                ('entity_id', models.CharField(max_length=128)),
                ('seq', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('transition', 'Transition'), ('correction', 'Correction'), ('action', 'Action'), ('ack', 'Ack'), ('flag', 'Flag'), ('rule_change', 'Rule Change')], max_length=16)),
                ('axis', models.CharField(max_length=32, null=True)),
                ('from_value', models.CharField(max_length=64, null=True)),
                ('to_value', models.CharField(max_length=64, null=True)),
                ('effective_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField()),
                ('rule', models.CharField(max_length=64)),
                ('evidence_ids', models.JSONField(default=list)),
                ('detail', models.JSONField(null=True)),
            ],
            options={
                'ordering': ['entity_type', 'entity_id', 'seq'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'seq'], name='core_timeli_entity__1b43a7_idx')],
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'entity_id', 'seq'), name='timeline_entity_seq_unique')],
            },
        ),
    ]
